name: Update SQL Server 2022 database

# This workflow requires the below secrets added to the repository for this to work
# TargetFile - The name you want the dacpac file to be called.
  # For example serverless.dacpac
# Azure_credentials - Required to create a temporary firewall rule for your agent
# ServerlessDB_Connection_String - Connection string for the destination database in the serverless SQL Pool


#Sets the trigger to update when update is pushed to a sql-action-v1-feature branch
on:
  push:
    branches: 
      - main

jobs:

  # Job to build and publish the dacpac
  ExtractDacpac:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Extract schema from an existing database in a serverless SQL Pool into a dacpac file
      - name: Extract Database schema
        run: |
          SqlPackage /Action:Extract /TargetFile:${{ secrets.TargetFile }} /p:VerifyExtraction=true /SourceServerName:${{ secrets.SQLPoolEndPoint }} /SourceDatabaseName:${{ secrets.SourceDB }} /SourceUser:${{ secrets.SQLPooluser }} /SourcePassword:${{ secrets.SQLPoolpw }}

      # Publish artifact
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ServerlessDacpac
          path: ${{ github.workspace }}

  # Deploy dacpac job
  DeployDacpac:
    # Set the dependency for the build job
    needs: ExtractDacpac
    # Easier to use Github-hosted runner if updating in GitHub
    runs-on: self-hosted

    # Steps to deploy the updates to a SQL Server 2022 Database
    steps:
      - name: download artifact containing dacpac
        # Dowloads Data artifact to dacpac folder
        uses: actions/download-artifact@v3.0.2
        with:
          name: ServerlessDacpac

      # Login using Azure credentials 
      # Required to add a temporary firewall rule for the runner
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.Azure_credentials }}


      # Installs dacpac
      # For this to work you MUST have two secrets specified, defaults in my repo are blank
      # One called SQLDB_SERVER which contains your logical SQL Server name
      # Requires a secret SQLDB_CONNECTION_STRING which contains connection string to the database in the serverless SQL Pool
      - name: Serverlesss SQL Pool  Deploy
        uses: Azure/sql-action@v2
        with:
          # The connection string, including authentication information, for the Azure SQL Database.
          connection-string: '${{ secrets.ServerlessDB_Connection_String }}'
          # Path to the dacpac file in the artifact
          path: './${{ secrets.TargetFile }}'
          # Action we want it to do, in this case 'Publish' the contents of the dacpac to the database
          action: 'publish'
